name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore PU.Users.sln

      - name: Build solution
        run: dotnet build PU.Users.sln --no-restore --configuration Release

      - name: Run tests
        run: dotnet test ./tests/PU.Users.Tests/PU.Users.Tests.csproj --verbosity normal



